const data = [
{
    "id": 0,
    "title": "Portofolio Page",
    "shortDescription": "Yes, this portofolio page is part of the portfolio",
    "linkToProject": "https://github.com/heliorrfreitas/space_invaders",
    "tags": ["game", "python", "programming", "pygame"]
}, 

{
    "id": 1,
    "title": "Game - Space Invaders",
    "shortDescription": "This is a simple version of the classic game Space Invaders.",
    "linkToProject": "https://github.com/heliorrfreitas/space_invaders",
    "tags": ["game", "python", "programming", "pygame"]
}, 

{
    "id": 2,
    "title": "Drawing App",
    "shortDescription": "This is a basic drawing app.",    
    "linkToProject": "https://github.com/heliorrfreitas/simple_drawing_app",
    "tags": ["draw", "javascript", "programming", "canvas"]
},


{
    "id": 3,
    "title": "Text Editor",
    "shortDescription": "Text editor made with Python.",
    "linkToProject": "https://github.com/heliorrfreitas/text-editor",
    "tags": [ "python", "programming"]
},

{
    "id": 4,
    "title": "Meme Generator",
    "shortDescription": "Meme generator made following the Learn React for Free class on Scrimba. The code has been refactored since in the class it was not built using React Hooks.",
    "linkToProject": "https://github.com/heliorrfreitas/meme_generator",
    "tags": [ "reactjs", "programming", "refactor"]
},

{
    "id": 5,
    "title": "Be The Hero",
    "shortDescription": "",
    "img": "https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60",
    "linkToProject": "https://github.com/heliorrfreitas/be-the-hero",
    "tags": ["javascript", "nodejs", "reactjs", "react native"]
},

{
    "id": 6,
    "title": "Ecoleta",
    "shortDescription": "I did this following a class from Rocketseat. This is an app that allows the people to register and locate recyple points.",
    "linkToProject": "https://github.com/heliorrfreitas/ecoleta",
    "tags": ["javascript", "nodejs", "reactjs", "react native"]
},


{
    "id": 7,
    "title": "Guess The Number",
    "shortDescription": "In this game the user tries to guess the random number generated by the computer. The user can turn on or off the tips in the game.",
    "linkToProject": "https://github.com/heliorrfreitas/guess-the-number",
    "tags": ["lisp", "common lisp", "programming"]
},


{
    "id": 8,
    "title": "Guess My Age",
    "shortDescription": "Simple game build to learn more about Lisp and get hands on code.",
    "linkToProject": "https://github.com/heliorrfreitas/guess-my-age",
    "tags": ["lisp", "common lisp", "programming"]
},

{
    "id": 9,
    "title": "Recipe App - Frontend",
    "shortDescription": "This is the frontend of an Recipe book app. This was built in Angular",
    "linkToProject": "https://github.com/heliorrfreitas/recipe_frontend_angular",
    "tags": ["angular", "frontend"]
},

{
    "id": 10,
    "title": "Recipe App - Backend",
    "shortDescription": "This is the backend of an Recipe book app. Built in Java using Spring.",
    "linkToProject": "https://github.com/heliorrfreitas/recipe_backend_java_spring",
    "tags": ["java", "backend", "spring"]
},


{
    "id": 11,
    "title": "Border Radius Generator",
    "shortDescription": "This app show in real time how the border radius will look if you change a value.",
    "linkToProject": "https://github.com/heliorrfreitas/css_border_radius_generator",
    "tags": [ "css", "frontend"]
},


{
    "id": 12,
    "title": "Base Converter (decimal, binary)",
    "shortDescription": "This is a react calculator that converters numbers from decimal to binary and vice versa.",
    "linkToProject": "https://github.com/heliorrfreitas/decimal_to_binary_and_binary_to_decimal",
    "tags": ["reactjs", "binary to decimal", "decimal to binary"]
},


]

export default data